### ISSUE TITLE
Improve syntax highlighter

### ISSUE THREAD

**Issue by abelriboulot** [windsorio/browse#19]
Relevant file: https://github.com/windsorio/browse/blob/master/packages/vscode/syntaxes/browse.tmLanguage.json
Entire grammar for browse: https://github.com/windsorio/browse/blob/master/packages/parser/lib/browse.ohm
Vscode ref: https://github.com/microsoft/vscode/blob/master/extensions/javascript/syntaxes/JavaScript.tmLanguage.json

**Comment by pranaygp** [comment]
Closed by f399e68
