### ISSUE TITLE
Allow passing in custom puppeteer options

### ISSUE THREAD

**Issue by boatengyeboah** [windsorio/browse#86]
Allow user to pass in their own custom `puppeteerOptions` for the browser. I will be happy to add this functionality however I have no clue so if you can give me some pointers :)

**Comment by pranaygp** [comment]
This is the file you need to look at: https://github.com/windsorio/browse/blob/master/packages/web/lib/browser.js

The actual puppeteer browser gets created here on the very first call to `visit`. We have a rough definition of how scoping works, so basically, there's (probably) only ever going to be one `browser` scope on any application which holds the browser objects, and all the pages get created and managed using the `page` scope (which is in the same directory, as page.js)

for now, one way I'd like to do this is to just have a `config` rule of some sort that takes a RuleSet as an argument. The `set` in the ruleset can be overridden to set config options, which are then used when the browser is actually started up for the first time

`page` has something similar already. look at this for inspiration: https://github.com/windsorio/browse/blob/master/packages/web/lib/page.js#L113-L130

cc. @atfaust2, who wrote most of the code I mentioned

**Comment by pranaygp** [comment]
oh, you may want to call if `browserConfig` and rename the rule in page.js to `pageConfig`. Otherwise we can't access them both from inside a page scope

**Comment by pranaygp** [comment]
Now available in `pre`. Thanks @boatengyeboah
